config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    member do
      get "add_subscriber"
      delete "remove_subscriber"
      delete "admin_force_remove_subscriber"
      get "add_thumbs_up"
      delete "remove_thumbs_up"
    end

    resources :comments, only: [:create]
  end

  resources :notifications, only: [:index] do
    collection do
      get :counter
      delete :destroy_all
    end
  end

  resources :users, only: [:index] do
    member do
      get "give_user_admin"
      delete "revoke_user_admin"
    end
  end

  get "auth/login" => "auth#login"
  get "auth/logout" => "auth#logout"
  match "auth/:provider/callback" => "auth#callback", via: [:get, :post]
  get "auth/failure" => "auth#failure"
  get "ping" => "application#ping"
  root to: "projects#index"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :bigint(8)        not null, primary key
#  name              :string
#  email             :string           indexed
#  profile_image_url :text
#  is_admin          :boolean
#  is_superuser      :boolean
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class User < ApplicationRecord

  has_many :projects, foreign_key: :owner_id
  has_and_belongs_to_many :subscriptions, class_name: "Project"
  has_many :comments, foreign_key: :owner_id
  has_many :notifications, foreign_key: :user_target_id
  has_many :thumbs_up, foreign_key: :creator_id

  after_save :validate_profile_image!, if: :should_validate_profile_image?

  validate :allowed_domain

  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def validate_profile_image!
    return unless profile_image_url
    require "rest_client"
    begin
      response_code = RestClient.head(profile_image_url).code
    rescue Exception
    ensure
      Rails.logger.error "Removing user #{self.id} image '#{profile_image_url}' because was not reachable."
      remove_profile_image_url! if response_code != 200
    end
  end

  private
  def should_validate_profile_image?
    true if Rails.env.production?
  end

  def remove_profile_image_url!
    update_attributes!(profile_image_url: nil)
  end

  def allowed_domain
    return if Settings.allowed_domain.blank?
    errors.add(:email, "domain not allowed") unless self.email.match("@#{Settings.allowed_domain}")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :validate_admin_user
  before_action :check_for_superuser, only: [:revoke_user_admin]
  before_action :find_user, except: [:index]

  def index
    @users = User.all.order(:name)
  end

  def give_user_admin
    @user.update!(is_admin: true)
    redirect_to users_url, notice: "#{@user.name} is now an admin."
  end

  def revoke_user_admin
    @user.update!(is_admin: false)
    redirect_to users_url, notice: "#{@user.name} is no longer an admin."
  end

  private
  def check_for_superuser
    return unless @user.is_superuser
    flash[:error] = "You can not remove the admin power of this user."
    redirect_to root_url
  end

  def find_user
    @user ||= User.find(params[:id])
  end
end

app/views/users/index.html.erb
<div class="page-header">
  <h1>Users <span class="label label-default"><%= @users.count %></span></h1>
</div>

<div class="row users">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th></th>
        <th>Name</th>
        <th>Email</th>
        <th>Labels</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><img class="img-square" width="45px" src="<%= user_profile_image(user) %>" alt="<%= user.name %>" title="<%= user.name %>"></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <div>
              <span class="label label-default"><%= user.projects.count %> Projects</span>
              <span class="label label-default"><%= user.comments.count %> Comments</span>
              <span class="label label-default"><%= user.thumbs_up.count %> Thumbs up</span>
            </br>
              <span class="label label-default"><%= user.subscriptions.count %> Subscriptions</span>
              <span class="label label-default"><%= user.notifications.count %> Notifications</span>
            </div>
          </td>
          <td>
            <% if user.is_superuser %>
            <% elsif user.is_admin %>
              <%= link_to revoke_user_admin_user_url(user), method: :delete, data: { confirm: 'Are you sure to revoke admin of this user?' }, class: 'btn btn-danger' do %>
                <span class="glyphicon glyphicon-remove"></span>
                Revoke Admin
              <% end %>
            <% else %>
              <%= link_to give_user_admin_user_url(user), class: 'btn btn-primary' do %>
                <span class="glyphicon glyphicon glyphicon-flash"></span>
                Give Admin
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>