config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    member do
      get "add_subscriber"
      delete "remove_subscriber"
      delete "admin_force_remove_subscriber"
      get "add_thumbs_up"
      delete "remove_thumbs_up"
    end

    resources :comments, only: [:create]
  end

  resources :notifications, only: [:index] do
    collection do
      get :counter
      delete :destroy_all
    end
  end

  resources :users, only: [:index] do
    member do
      get "give_user_admin"
      delete "revoke_user_admin"
    end
  end

  get "auth/login" => "auth#login"
  get "auth/logout" => "auth#logout"
  match "auth/:provider/callback" => "auth#callback", via: [:get, :post]
  get "auth/failure" => "auth#failure"
  get "ping" => "application#ping"
  root to: "projects#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="<%= Settings.company_name %> - <%= Settings.hackathon_name %> website">
  <meta name="author" content="<%= Settings.company_name %>">
  <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
  <link rel="manifest" href="/favicons/manifest.json">
  <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="theme-color" content="#ffffff">
  <title><%= Settings.company_name %> - <%= Settings.hackathon_name %></title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <% if ENV["GOOGLE_ANALYTICS_GTAG"] %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV["GOOGLE_ANALYTICS_GTAG"] %>"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '<%= ENV["GOOGLE_ANALYTICS_GTAG"] %>');
    </script>
  <% end %>

</head>
<body>
  <nav class="navbar navbar-inverse navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#{Settings.company_name} - #{Settings.hackathon_name}", editions_active_now_url, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <% if current_user %>
        <ul class="nav navbar-nav">
          <% if any_edition_active_now %>
          <li><a href="<%= edition_projects_url(any_edition_active_now) %>"><%= any_edition_active_now.title %></a></li>
          <% end %>
          <li><a href="<%= editions_url %>">Editions</a></li>
          <li><a href="<%= notifications_url %>">Notifications <span class="badge notifications_count"><%= notifications_counter %></span></a></li>
          <% if current_user && current_user.is_admin %>
            <li><a href="<%= users_url %>">Users</a></li>
          <% end %>
        </ul>
          <p class="navbar-text navbar-right avatar">
              <img src="<%= user_profile_image(@current_user) %>" class="img-circle"><%= current_user.name %>
            <a href="<%= auth_logout_url %>" class="btn btn-sm btn-default">
              <i class="glyphicon glyphicon-log-out"></i>
              Logout
            </a>
          </p>
        <% end %>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == "error" ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>

  <br />
  <footer class="footer">
     <div class="container text-right">
       <p class="text-muted">&copy; <a target="_blank" href="https://github.com/rafaelbiriba/hackathon_organizer">Hackathon Organizer</a> (<%= HackathonOrganizer::VERSION %>)</p>
     </div>
   </footer>
</body>
</html>